"""initial schema

Revision ID: 113e2803d038
Revises: 
Create Date: 2026-01-26 17:22:35.386245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113e2803d038'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_clicks', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('my_clicks', sa.Integer(), nullable=False),
    sa.Column('selected_cosmetic', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('unlocked_cosmetics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('cosmetic_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['profiles.device_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'cosmetic_id', name='uq_device_cosmetic')
    )
    op.create_index('ix_device_id', 'unlocked_cosmetics', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_id', table_name='unlocked_cosmetics')
    op.drop_table('unlocked_cosmetics')
    op.drop_table('profiles')
    op.drop_table('global_state')
    # ### end Alembic commands ###
